// Email Service with PDF Report Generation
// Daily automated email alerts with detailed PDF reports

const EmailService = {
  // Email configuration
  config: {
    enabled: true,
    recipient: 'admin@everse.in', // Change this
    schedule: {
      enabled: true,
      time: '09:00', // 9 AM daily
      timezone: 'Asia/Kolkata'
    },
    smtp: {
      // Will use Google Apps Script or external service
      service: 'gmail',
      useServiceAccount: true
    }
  },

  // Generate daily report data
  async generateDailyReport() {
    try {
      const data = await loadAllData(true); // Force refresh
      const kpis = calculateKPIs();
      const user = GoogleAuth.getCurrentUser();
      
      // Get recent activity (last 24 hours)
      const logs = await AuditTrail.loadLogs({
        dateFrom: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        limit: 100
      });
      
      // Get low stock items
      const lowStockItems = [];
      (data.inventory || []).forEach(product => {
        CONFIG.WAREHOUSES.forEach(wh => {
          const stock = product.stock[wh] || 0;
          const reorderLevel = product.reorderLevel || 0;
          if (stock > 0 && stock < reorderLevel) {
            lowStockItems.push({
              product: product.name,
              warehouse: wh,
              stock: stock,
              reorderLevel: reorderLevel
            });
          }
        });
      });
      
      // Get unfulfilled orders
      const unfulfilledOrders = (data.orders || []).filter(o => {
        const status = (o.status || '').toUpperCase();
        return status === 'PROCESSING' || status === 'SHIPPED';
      });
      
      // Get gaps
      const gaps = data.gaps || [];
      
      const report = {
        date: new Date().toISOString().split('T')[0],
        generatedBy: user?.email || 'System',
        kpis: {
          totalValue: kpis.totalValue,
          totalNumber: kpis.totalNumber,
          totalGaps: kpis.totalGaps,
          pendingOrders: kpis.unfulfilled || 0
        },
        lowStockItems: lowStockItems,
        unfulfilledOrders: unfulfilledOrders.length,
        gaps: gaps.length,
        recentActivity: logs.slice(0, 20),
        summary: {
          totalOrders: data.orders?.length || 0,
          totalProducts: data.inventory?.length || 0,
          totalMovements: data.movements?.length || 0
        }
      };
      
      return report;
    } catch (error) {
      console.error('Generate daily report error:', error);
      throw error;
    }
  },

  // Generate PDF from report data
  async generatePDFReport(report) {
    try {
      // Use jsPDF or html2pdf library
      // For now, return HTML that can be converted to PDF
      const html = this.generateReportHTML(report);
      
      // Note: Actual PDF generation requires a library like jsPDF or html2pdf
      // Or use Google Apps Script to generate PDF server-side
      
      return {
        html: html,
        // For server-side PDF generation via Google Apps Script
        data: report
      };
    } catch (error) {
      console.error('Generate PDF error:', error);
      throw error;
    }
  },

  // Generate HTML report
  generateReportHTML(report) {
    const date = new Date(report.date).toLocaleDateString('en-IN', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Arial, sans-serif; margin: 20px; }
    .header { background: #667eea; color: white; padding: 20px; border-radius: 5px; }
    .section { margin: 20px 0; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background-color: #f2f2f2; }
    .kpi { display: inline-block; margin: 10px; padding: 15px; background: #f8f9fa; border-radius: 5px; }
    .kpi-value { font-size: 24px; font-weight: bold; color: #667eea; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Everse Inventory Management - Daily Report</h1>
    <p>Date: ${date}</p>
    <p>Generated by: ${report.generatedBy}</p>
  </div>
  
  <div class="section">
    <h2>Key Performance Indicators</h2>
    <div class="kpi">
      <div>Total Inventory Value</div>
      <div class="kpi-value">${typeof formatCurrency !== 'undefined' ? formatCurrency(report.kpis.totalValue) : '₹' + (report.kpis.totalValue || 0).toLocaleString('en-IN')}</div>
    </div>
    <div class="kpi">
      <div>Total Products</div>
      <div class="kpi-value">${report.kpis.totalNumber}</div>
    </div>
    <div class="kpi">
      <div>Total Gaps</div>
      <div class="kpi-value">${report.kpis.totalGaps}</div>
    </div>
    <div class="kpi">
      <div>Pending Orders</div>
      <div class="kpi-value">${report.kpis.pendingOrders}</div>
    </div>
  </div>
  
  <div class="section">
    <h2>Low Stock Items</h2>
    <table>
      <thead>
        <tr>
          <th>Product</th>
          <th>Warehouse</th>
          <th>Current Stock</th>
          <th>Reorder Level</th>
        </tr>
      </thead>
      <tbody>
        ${report.lowStockItems.map(item => `
          <tr>
            <td>${item.product}</td>
            <td>${item.warehouse}</td>
            <td>${item.stock}</td>
            <td>${item.reorderLevel}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </div>
  
  <div class="section">
    <h2>Unfulfilled Orders</h2>
    <p>Total: ${report.unfulfilledOrders} orders</p>
  </div>
  
  <div class="section">
    <h2>Gaps Summary</h2>
    <p>Total gaps: ${report.gaps}</p>
  </div>
  
  <div class="section">
    <h2>Recent Activity (Last 24 Hours)</h2>
    <table>
      <thead>
        <tr>
          <th>Time</th>
          <th>User</th>
          <th>Action</th>
          <th>Details</th>
        </tr>
      </thead>
      <tbody>
        ${report.recentActivity.map(log => `
          <tr>
            <td>${new Date(log.timestamp).toLocaleString()}</td>
            <td>${log.user}</td>
            <td>${log.action}</td>
            <td>${log.details || '-'}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </div>
  
  <div class="section">
    <p><small>This is an automated daily report. For questions, contact admin@everse.in</small></p>
  </div>
</body>
</html>
    `;
  },

  // Send email via Google Apps Script
  async sendEmail(subject, body, pdfData = null) {
    try {
      // Note: This requires a Google Apps Script web app
      // The script will handle email sending via Gmail API
      
      const emailData = {
        to: this.config.recipient,
        subject: subject,
        body: body,
        pdf: pdfData,
        html: true
      };
      
      // Call Google Apps Script web app
      if (CONFIG.EMAIL_SERVICE_URL) {
        const response = await fetch(CONFIG.EMAIL_SERVICE_URL, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(emailData)
        });
        
        if (response.ok) {
          return { success: true };
        } else {
          throw new Error('Email service failed');
        }
      } else {
        // Fallback: Log to console (for development)
        console.log('Email would be sent:', emailData);
        return { success: true, simulated: true };
      }
    } catch (error) {
      console.error('Send email error:', error);
      return { success: false, error: error.message };
    }
  },

  // Send daily report
  async sendDailyReport() {
    try {
      const report = await this.generateDailyReport();
      const pdfData = await this.generatePDFReport(report);
      const html = pdfData.html;
      
      const subject = `Daily Inventory Report - ${report.date}`;
      
      await this.sendEmail(subject, html, pdfData);
      
      await logAuditEvent({
        action: 'EMAIL',
        entity: 'Report',
        details: `Daily report sent to ${this.config.recipient}`
      });
      
      return { success: true };
    } catch (error) {
      console.error('Send daily report error:', error);
      return { success: false, error: error.message };
    }
  },

  // Schedule daily reports
  scheduleDailyReports() {
    if (!this.config.schedule.enabled) return;
    
    // Check if it's time to send
    const checkAndSend = () => {
      const now = new Date();
      const scheduleTime = this.config.schedule.time.split(':');
      const scheduleHour = parseInt(scheduleTime[0]);
      const scheduleMinute = parseInt(scheduleTime[1]);
      
      // Check if current time matches schedule (within 5 minutes)
      if (now.getHours() === scheduleHour && 
          now.getMinutes() >= scheduleMinute && 
          now.getMinutes() < scheduleMinute + 5) {
        // Check if already sent today
        const lastSent = localStorage.getItem('last_daily_report');
        const today = new Date().toISOString().split('T')[0];
        
        if (lastSent !== today) {
          this.sendDailyReport().then(() => {
            localStorage.setItem('last_daily_report', today);
          });
        }
      }
    };
    
    // Check every minute
    setInterval(checkAndSend, 60 * 1000);
    
    // Also check immediately
    checkAndSend();
  }
};

// Export
window.EmailService = EmailService;

// Auto-schedule on load
if (EmailService.config.schedule.enabled) {
  EmailService.scheduleDailyReports();
}

